# Python Interview Questions (61-70)

---



### Q61. What is the use of self in Python?


In Python, **self** is a convention used to represent the instance of the class in a method. It is the first parameter of any method defined in a class and refers to the instance of the class. The use of self allows you to access and modify the attributes of the instance within the class.

A simple example to illustrate the use of self in a class:

In [1]:
class MyClass:
    def __init__(self, value):
        self.value = value

    def print_value(self):
        print(self.value)

    def update_value(self, new_value):
        self.value = new_value

# Creating an instance of MyClass
obj = MyClass(10)

# Accessing and printing the value attribute
obj.print_value()  # Output: 10

# Updating the value attribute
obj.update_value(20)

# Printing the updated value
obj.print_value()  # Output: 20

10
20


In this example, self is used as the first parameter in the __init__, print_value, and update_value methods. When you create an instance of MyClass (e.g., obj = MyClass(10)), the instance is passed as the self parameter implicitly. This allows you to work with the instance's attributes and perform operations on them within the class methods.

It's important to note that self is just a convention, and you could technically use any name for this parameter, but using self is a widely accepted and recommended convention in the Python community.

### Q62. What are the different types of variables in Python OOP?



In Python, when working with Object-Oriented Programming (OOP), variables in a class can be categorized into two main types: instance variables and class variables.

##### 1. Instance Variables:

- **Definition:** These are variables that are bound to the instance of a class.
- **Scope:** Each instance of the class has its own copy of instance variables.
- **Access:** They are accessed using the **self** keyword within class methods.
- **Purpose:** Used for storing individual characteristics of objects.

In [4]:
class MyClass:
    def __init__(self, name, age):
        self.name = name  # Instance variable
        self.age = age    # Instance variable

##### 2. Class Variables:

- **Definition:** These are variables that are shared among all instances of a class.
- **Scope:** Shared by all instances of the class.
- **Access:** They are typically accessed using the class name.
- **Purpose:** Used for storing attributes that are common to all instances of the class.

In [5]:
class MyClass:
    class_variable = 0  # Class variable

    def __init__(self, name, age):
        self.name = name  # Instance variable
        self.age = age    # Instance variable
        MyClass.class_variable += 1  # Accessing and modifying class variable

In the example above, class_variable is a class variable, and name and age are instance variables. Class variables are shared among all instances, while each instance has its own set of instance variables.

It's important to note that instance variables are typically defined within the __init__ method using the self keyword, while class variables are defined directly within the class body but outside any method. Class variables can be accessed using the class name (MyClass.class_variable), whereas instance variables are accessed using the self keyword (self.name, self.age).

Understanding the distinction between instance and class variables is crucial for effective use of Python's object-oriented features.

### Q63. What are the different types of methods in Python OOP?

In Python's Object-Oriented Programming (OOP), methods in a class can be categorized into three main types: instance methods, class methods, and static methods.

##### 1. Instance Methods:

- **Definition:** These are the most common type of methods and are associated with an instance of a class.
- **Access:** They have access to the instance and its attributes through the self parameter.
- **Purpose:** Used for operations that involve the attributes of an instance.

In [6]:
class MyClass:
    def __init__(self, value):
        self.value = value

    def print_value(self):
        print(self.value)

    def update_value(self, new_value):
        self.value = new_value

##### 2. Class Methods:

- **Definition:** These methods are bound to the class rather than an instance of the class.
- **Access:** They have access to the class itself through the cls parameter.
- **Declaration:** Decorated with @classmethod.
- **Purpose:** Used for operations that involve the class and its class variables.

In [7]:
class MyClass:
    class_variable = 0

    def __init__(self, value):
        self.value = value

    @classmethod
    def increment_class_variable(cls):
        cls.class_variable += 1

##### 3. Static Methods:

- **Definition:** These methods are not bound to either the instance or the class.
- **Access:** They do not have access to self or cls by default.
- **Declaration:** Decorated with @staticmethod.
- **Purpose:** Used for operations that do not depend on the instance or class state.

In [8]:
class MathOperations:
    @staticmethod
    def add(x, y):
        return x + y

In the examples above, print_value and update_value are instance methods, increment_class_variable is a class method, and add is a static method. Instance methods and class methods are defined with the def keyword, while static methods use the @staticmethod decorator.

Choosing between these types of methods depends on the nature of the operation you are performing. Instance methods are most common, but class methods and static methods offer flexibility for different use cases.

### Q64. What is inheritance, and how is it useful?

Inheritance is a fundamental concept in object-oriented programming (OOP) that allows a new class, called a subclass or derived class, to inherit attributes and behaviors (methods) from an existing class, called a superclass or base class. The subclass can then extend or modify the inherited characteristics. This promotes code reuse, abstraction, and the organization of code in a hierarchical and modular way.

##### Key Concepts in Inheritance:

###### 1. Superclass (Base Class):

- The existing class whose attributes and methods are inherited.
- It is also referred to as the parent class.

In [9]:
class Animal:
    def __init__(self, name):
        self.name = name

    def speak(self):
        pass

###### 2. Subclass (Derived Class):

- The new class that inherits from the superclass.
- It is also referred to as the child class.

In [10]:
class Dog(Animal):
    def speak(self):
        return "Woof!"

Example:

In [11]:
class Animal:
    def __init__(self, name):
        self.name = name

    def speak(self):
        return "Generic animal sound"

class Dog(Animal):
    def speak(self):
        return "Woof!"

class Cat(Animal):
    def speak(self):
        return "Meow!"

# Using the classes
dog = Dog("Buddy")
cat = Cat("Whiskers")

print(dog.name)        # Output: Buddy
print(dog.speak())      # Output: Woof!

print(cat.name)        # Output: Whiskers
print(cat.speak())      # Output: Meow!

Buddy
Woof!
Whiskers
Meow!


##### Benefits of Inheritance:

######  
1. Code Reusability:

- Inheritance allows you to reuse code from existing classes, reducing redundancy and promoting a modular code structure.

2. Hierarchy and Organization:

- Inheritance provides a way to model and represent relationships between classes in a hierarchical structure, making the code more organized and easier to understand.

3. Overriding and Extending:

- Subclasses can override methods from the superclass, providing specific implementations. They can also add new methods or attributes to extend the functionality.

4. Polymorphism:

- Inheritance supports polymorphism, allowing objects of the subclass to be treated as objects of the superclass. This enables flexibility and dynamic behavior.

5. Maintainability:

- Changes made to the superclass are automatically reflected in the subclasses, promoting easier maintenance and updates.

In summary, inheritance is a powerful mechanism in OOP that fosters code reuse, abstraction, and the creation of well-organized class hierarchies. It contributes to the development of more modular, scalable, and maintainable software systems.

### Q65.  What are access specifiers?


In Python, access specifiers are used to control the visibility and accessibility of class members (attributes and methods). Access specifiers determine how these members can be accessed from outside the class. While some programming languages have explicit keywords like public, private, and protected to define access levels, Python uses naming conventions to achieve similar results.

The commonly used access specifiers in Python are:

##### 1. Public (No Prefix):

- Members are accessible from anywhere, both within and outside the class.
- No specific syntax or naming convention is used. Members without any prefix are considered public.

In [12]:
class MyClass:
    def __init__(self):
        self.public_variable = "I am public"

    def public_method(self):
        return "This is a public method"

##### 2. Protected (Single Underscore Prefix _):

- Members are accessible within the class and its subclasses (if any).
- It is a convention and not enforced by the language.

In [13]:
class MyClass:
    def __init__(self):
        self._protected_variable = "I am protected"

    def _protected_method(self):
        return "This is a protected method"

##### 3. Private (Double Underscore Prefix __):

- Members are only accessible within the class. They are not directly accessible from outside the class or its subclasses.
- The double underscore prefix invokes name mangling, making it harder to access the member from outside.

In [14]:
class MyClass:
    def __init__(self):
        self.__private_variable = "I am private"

    def __private_method(self):
        return "This is a private method"

Example:

In [15]:
class MyClass:
    def __init__(self):
        self.public_variable = "I am public"
        self._protected_variable = "I am protected"
        self.__private_variable = "I am private"

    def public_method(self):
        return "This is a public method"

    def _protected_method(self):
        return "This is a protected method"

    def __private_method(self):
        return "This is a private method"

# Using the class
obj = MyClass()

print(obj.public_variable)        # Accessing public variable
print(obj.public_method())         # Accessing public method

print(obj._protected_variable)     # Accessing protected variable (convention)
print(obj._protected_method())      # Accessing protected method (convention)

# Attempting to access private members directly will result in an AttributeError
# print(obj.__private_variable)     # This will raise an AttributeError
# print(obj.__private_method())      # This will raise an AttributeError

I am public
This is a public method
I am protected
This is a protected method


It's important to note that Python does not enforce strict encapsulation, and access specifiers are more of a convention than a strict rule. Developers are expected to follow these conventions to indicate the intended visibility of class members.

### Q66. In numpy, how is array[:, 0] is different from array[:[0]]?


In NumPy, the expressions array[:, 0] and array[:, [0]] have different meanings and result in different types of arrays.

##### 1. array[:, 0]:

- This expression selects all rows of the array and the 0th column.
- It returns a 1-dimensional array (or a slice) containing the elements from the specified column.

In [16]:
import numpy as np

# Creating a 2D array
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

result = array[:, 0]
print(result)

[1 4 7]


##### 2. array[:, [0]]:

- This expression also selects all rows of the array but returns a 2-dimensional array with a single column.
- The extra square brackets around 0 indicate that you want to select the 0th column as a 2D array, resulting in a column vector.

In [17]:
import numpy as np

# Creating a 2D array
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

result = array[:, [0]]
print(result)

[[1]
 [4]
 [7]]


In summary, array[:, 0] returns a 1D array with the elements from the specified column, while array[:, [0]] returns a 2D array with a single column, often referred to as a column vector. The use of double brackets in array[:, [0]] is used to explicitly indicate that you want a 2D result. This distinction is important when dealing with operations that expect specific array shapes.

### Q67. How can we check for an array with only zeros?

In NumPy, you can check if an array contains only zeros using the np.all() function in combination with the equality operator (==). The np.all() function checks whether all elements of the array satisfy a given condition.

Example:

In [18]:
import numpy as np

# Create an array
arr = np.array([0, 0, 0, 0])

# Check if all elements are zero
are_all_zeros = np.all(arr == 0)

# Print the result
print(are_all_zeros)

True


In this example, np.all(arr == 0) checks if all elements of the array arr are equal to zero. The result will be a boolean value (True if all elements are zero, and False otherwise).

If you're dealing with a multi-dimensional array and want to check if all elements are zero along a specific axis or in the entire array, you can use the np.all() function along with the axis parameter:

In [19]:
import numpy as np

# Create a 2D array
arr_2d = np.array([[0, 0, 0],
                   [0, 0, 0]])

# Check if all elements are zero along axis 1 (columns)
are_all_zeros_along_columns = np.all(arr_2d == 0, axis=1)

# Print the result
print(are_all_zeros_along_columns)

[ True  True]


This will check if all elements along each column are zero, and the result will be a boolean array indicating which columns satisfy the condition.

Remember that when working with floating-point numbers, you might want to use a tolerance level (e.g., np.allclose()) instead of exact equality due to potential floating-point precision issues.

### Q68.  How can we concatenate two arrays?


In NumPy, you can concatenate two arrays along a specified axis using the np.concatenate() function or, for simplicity, you can use the np.vstack() (vertical stack) or np.hstack() (horizontal stack) functions for concatenation along the first axis (rows) or second axis (columns), respectively.

##### 1. Using np.concatenate():

In [20]:
import numpy as np

# Create two arrays
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6]])

# Concatenate along the first axis (rows)
concatenated_array = np.concatenate((arr1, arr2), axis=0)

print(concatenated_array)

[[1 2]
 [3 4]
 [5 6]]


##### 2. Using np.vstack():

In [21]:
import numpy as np

# Create two arrays
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6]])

# Vertical stack
concatenated_array = np.vstack((arr1, arr2))

print(concatenated_array)

[[1 2]
 [3 4]
 [5 6]]


##### 3. Using np.hstack():

In [22]:
import numpy as np

# Create two arrays
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6]])

# Horizontal stack
concatenated_array = np.hstack((arr1, arr2.T))  # Transpose arr2 to match dimensions

print(concatenated_array)

[[1 2 5]
 [3 4 6]]


In these examples, arr1 and arr2 are concatenated along the rows using np.concatenate() and np.vstack(). For horizontal concatenation, np.hstack() is used, and the arr2.T is used to transpose arr2 before concatenation to match dimensions.

Choose the appropriate method based on the concatenation axis and the desired outcome. The axis parameter in np.concatenate() allows you to specify the axis along which the concatenation should occur.

### Q69. How can we check for the local maxima of an array?

You can find the local maxima of a 1-dimensional array in NumPy using the scipy.signal module's argrelextrema function. This function returns the indices of relative extrema (maxima or minima) of a 1D array. To find local maxima, you can specify the order parameter to control the number of points surrounding each point to use for the comparison.

Example:

In [23]:
import numpy as np
from scipy.signal import argrelextrema

# Create a 1D array
arr = np.array([1, 3, 7, 1, 2, 6, 4, 8, 5])

# Find local maxima indices
maxima_indices = argrelextrema(arr, np.greater, order=1)

# Get values at local maxima indices
local_maxima_values = arr[maxima_indices]

print("Indices of local maxima:", maxima_indices)
print("Values at local maxima:", local_maxima_values)

Indices of local maxima: (array([2, 5, 7]),)
Values at local maxima: [7 6 8]


In this example, the argrelextrema function is used with the np.greater comparison function to find local maxima. The order parameter is set to 1, meaning that a point must be greater than its neighbors on both sides to be considered a local maximum.

Note that argrelextrema returns a tuple, and the local maxima indices are obtained by accessing the first element of the tuple (maxima_indices[0]).

Keep in mind that this approach identifies only relative maxima, meaning points that are higher than their neighbors. If you need to find absolute maxima, you may need to combine this approach with additional conditions or post-processing depending on your specific requirements.

### Q70. What’s the difference between split() and array_split()?


In NumPy, split() and array_split() are two functions used for splitting an array into multiple subarrays. However, there is a key difference between the two:

##### 1. numpy.split():

- The split() function is used for splitting an array into equal-sized subarrays along a specified axis.
- It takes three parameters: the array to be split, the number of equal-sized subarrays to create, and the axis along which the split should occur.
- The array must be evenly divisible by the number of splits along the specified axis.

In [24]:
import numpy as np

# Creating an array
arr = np.array([1, 2, 3, 4, 5, 6])

# Splitting the array into 3 equal-sized subarrays along axis 0
result = np.split(arr, 3, axis=0)

print(result)

[array([1, 2]), array([3, 4]), array([5, 6])]


##### 2. numpy.array_split():

- The array_split() function is used for splitting an array into subarrays of potentially unequal sizes.
- It takes two parameters: the array to be split and the number of subarrays to create.
- The array does not need to be evenly divisible by the number of splits.

In [25]:
import numpy as np

# Creating an array
arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Splitting the array into 3 subarrays (unequal sizes)
result = np.array_split(arr, 3)

print(result)

[array([1, 2, 3]), array([4, 5]), array([6, 7])]


In summary, the main difference is that split() requires the array to be evenly divisible by the number of splits along the specified axis, whereas array_split() allows for unequal-sized subarrays. If you need equal-sized subarrays, and the array is evenly divisible, you can use either function. If you need flexibility in handling arrays that are not evenly divisible, array_split() is more suitable.